### ISSUE TITLE
当我训练road_waymo数据集时出现了shutil.SameFileError:的错误，请问怎么解决？

### ISSUE THREAD

**Issue by XinyiWang1123** [salmank255/ROAD_Waymo_Baseline#5]
Traceback (most recent call last):
  File "main.py", line 348, in <module>
    main()
  File "main.py", line 323, in main
    train(args, net, val_dataset, train_dataset)
  File "/data/ROAD_Waymo_Baseline/train.py", line 25, in train
    utils.copy_source(source_dir)
  File "/data/ROAD_Waymo_Baseline/modules/utils.py", line 76, in copy_source
    shutil.copy2(os.path.join(dirpath, file), source_dir)
  File "/opt/conda/lib/python3.7/shutil.py", line 266, in copy2
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/opt/conda/lib/python3.7/shutil.py", line 104, in copyfile
    raise SameFileError("{!r} and {!r} are the same file".format(src, dst))
shutil.SameFileError: './road_waymo/cache/resnet50I3D600-Pkinetics-b4s8x1x1-road_waymotn-h3x3x3/source/inference_dataset.py' and '/data/ROAD_Waymo_Baseline/road_waymo/cache/resnet50I3D600-Pkinetics-b4s8x1x1-road_waymotn-h3x3x3//source/inference_dataset.py' are the same file

**Comment by salmank255** [comment]
You are getting this error due to copying the source files. I added an exception for that please pull the recent changes and run the code again.
