### ISSUE TITLE
How to submit test phase result

### ISSUE THREAD

**Issue by xingexjj** [salmank255/ROAD_Waymo_Baseline#9]
Hello, I don't know how to name the videos in the test phase, and I encountered this error:

Traceback (most recent call last):
  File "/code/scripts/workers/submission_worker.py", line 504, in run_submission
    submission_metadata=submission_serializer.data,
  File "/tmp/tmpapg0hxt4/compute/challenge_data/challenge_2043/main.py", line 233, in evaluate
    iou_thresh=0.1)
  File "/tmp/tmpapg0hxt4/compute/challenge_data/challenge_2043/road_eval.py", line 252, in evaluate_tubes
    det_tubes[videoname] = detections[label_type][videoname]
KeyError: 'val_00119'

Could you please let me know the correct video name?

**Comment by wenba0** [comment]
hello,how can I eval test data(val_00000.mp4--val_00201.mp4) via trained model,I caught a problem when initialize dataset,missing this file
<img width="721" alt="图片" src="https://github.com/salmank255/ROAD_Waymo_Baseline/assets/56385650/91241d9a-db24-488c-b548-a8392908eb1e">

**Comment by salmank255** [comment]
Hi @xingexjj,

From the error, it looks like you don't have predictions for the video 'val_00119'. The name is correct but please check your pkl file you are missing one video.

**Comment by salmank255** [comment]
Hi @jojolee123,

The file you are mentioning is a test file to be fair and avoid cheating we are not providing the test file. What you need to do is first convert the videos into frames the same way you did it for training videos, then change the dataloader a bit i.e., to load only frames in sequence the same way we are creating a list of ids in our dataloader then follow the below instructions:

Submission guidelines


 Below we show an examples of the structure used to encode the tubes. Tube detection can be done for agent, action or event (triplet). For each respective categories, tubes are then indexed by video name. A detection file may contain only one category (e.g. action tubes only), or any combination of agent, action and event tubes.
 You are supposed to upload a .zip file containing your detections in .pkl file, that follow the same format as the output from [Baseline](https://github.com/salmank255/ROAD_Waymo_Baseline). To create the tube pickle file, please look at the make_tubes function [here](https://github.com/salmank255/ROAD_Waymo_Baseline/blob/1f785a09a54522a042bf45de8bdaa10d2eb15430/tubes.py#L201)
Additionally, please look [here](https://github.com/salmank255/ROAD_Waymo_Baseline/blob/1f785a09a54522a042bf45de8bdaa10d2eb15430/modules/tube_helper.py#L58) for more details in the tube_helper function here
Please check the ROAD: The ROad event Awareness Dataset for Autonomous Driving paper release [here](https://arxiv.org/pdf/2102.11585.pdf) and the official challenge website [here](https://sites.google.com/view/road-plus-plus/challenge). 

tubes = {
    # For the agent detection phase
    'agent': {
        # For each video
        'val_00000': [
            # For each tube
            # tube 1
            {   # class index
                'label_id': 0,
                # bounding box scores
                'scores': [0.11491841, 0.16743928, 0.16620131, 0.25436875, 0.3424321, 0.13464102],
                # bounding box coordinates (absolute)
                'boxes': [[473.2007, 229.3157, 485.1342, 255.87836],
                          [475.29144, 229.99019, 487.3297, 256.3758],
                          [476.7905, 231.2161, 488.5682, 256.20172],
                          [476.16983, 232.67128, 487.9435, 256.62274],
                          [477.0421, 233.207, 489.6095, 261.4667],
                          [476.92032, 231.34416, 489.44467, 258.55612]],
                # tube score
                'score': 0.2984004318714142,
                # frames across which the tube spans
                'frames': [3, 4, 5, 6, 7, 8]
            },
            # tube 2 ....etc
            {'label_id': 8,
             'scores': [0.00499768, 0.00780391, 0.00793609, 0.01454592, 0.00528766, 0.0064956],
             'boxes': [[473.2007, 229.3157, 485.1342, 255.87836],
                       [475.29144, 229.99019, 487.3297, 256.3758],
                       [476.7905, 231.2161, 488.5682, 256.20172],
                       [476.16983, 232.67128, 487.9435, 256.62274],
                       [477.0421, 233.207, 489.6095, 261.4667],
                       [476.92032, 231.34416, 489.44467, 258.55612]],
             'score': 0.011241009458899498,
             'frames': [3, 4, 5, 6, 7, 8]
             }],
        'val_00001': [
            {'label_id': 0,
             'scores': [0.31537667, 0.33871746, 0.38098595, 0.391808, 0.411738, 0.45692945, 0.4361148, 0.41504627,
                        0.33924338, 0.33919814],
             'boxes': [[233.39621, 229.62762, 250.89172, 270.01837],
                       [231.7886, 229.46082, 249.37988, 270.09534],
                       [233.13297, 228.26091, 249.87491, 270.66592],
                       [233.86197, 228.34746, 250.49533, 270.5857],
                       [234.741, 228.86885, 250.79462, 270.60886],
                       [235.85526, 228.73657, 251.91522, 270.3862],
                       [235.43227, 227.48727, 253.04256, 270.04684],
                       [236.68402, 227.16776, 254.13055, 270.15445],
                       [237.705, 225.65567, 255.68808, 272.31024],
                       [238.21509, 225.603, 256.12067, 272.79736]],
             'score': 0.4465221166610718,
             'frames': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
             },
            {'label_id': 2,
             'scores': [0.0550709, 0.03837099, 0.05360496, 0.06003099, 0.05830128, 0.0684725, 0.05991841, 0.05455188,
                        0.05517705, 0.03905908],
             'boxes': [[233.39621, 229.62762, 250.89172, 270.01837],
                       [231.7886, 229.46082, 249.37988, 270.09534],
                       [233.13297, 228.26091, 249.87491, 270.66592],
                       [233.86197, 228.34746, 250.49533, 270.5857],
                       [234.741, 228.86885, 250.79462, 270.60886],
                       [235.85526, 228.73657, 251.91522, 270.3862],
                       [235.43227, 227.48727, 253.04256, 270.04684],
                       [236.68402, 227.16776, 254.13055, 270.15445],
                       [237.705, 225.65567, 255.68808, 272.31024],
                       [238.21509, 225.603, 256.12067, 272.79736]],
             'score': 0.06425174325704575,
             'frames': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
             }
        ]
    }
 }

**Comment by xingexjj** [comment]
@salmank255 Thank you for your explanation. Here are two more questions:
1. What's the height/width of the bounding box in the submission file.
2. I notice that the deadline on eval.ai has changed. Do you delay the deadline?
![1691043889375](https://github.com/salmank255/ROAD_Waymo_Baseline/assets/127658947/be8c5497-7e4e-4469-87de-ab71a5770716)

**Comment by xingexjj** [comment]
> @salmank255 Thank you for your explanation. Here are two more questions:
> 
> 1. What's the height/width of the bounding box in the submission file.
> 2. I notice that the deadline on eval.ai has changed. Do you delay the deadline?
>    ![1691043889375](https://user-images.githubusercontent.com/127658947/258026551-be8c5497-7e4e-4469-87de-ab71a5770716.png)

I've handled the first problem. Now I only need to know if the deadline has been changed. Thank you!

**Comment by salmank255** [comment]
Hi @xingexjj,

The deadline has been extended by 25 days (to 31st of August 11:59 GMT) as we released the test data late.

**Comment by xingexjj** [comment]
> Hi @xingexjj,
> 
> The deadline has been extended by 25 days (to 31st of August 11:59 GMT) as we released the test data late.

Got it. Thank you for your explanation.
